apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: serviceb-abort
spec:
  destination:
    name: serviceb-service
  httpFault:
    abort:
      percent: 75
      httpStatus: 400
