#!/usr/bin/bash

# This script expects to read in the out put from docker images

template=deployment-template.yaml
regex="(.+)/(.*)(service)([ab])([^ ]*) (.*)"

while read -r line
do
  if [[ $line =~ $regex ]]
  then
    dockerid=${BASH_REMATCH[1]}
    service=${BASH_REMATCH[3]}${BASH_REMATCH[4]}
    deployment=${BASH_REMATCH[2]}${BASH_REMATCH[3]}${BASH_REMATCH[4]}${BASH_REMATCH[5]}

    while IFS='' read -r line || [[ -n "$line" ]]; do
      if [[ "$line" =~ (.*)SERVICE(.*) ]]
      then
        echo "${BASH_REMATCH[1]}${service}${BASH_REMATCH[2]}"
      elif [[ "$line" =~ (.*)DEPLOYMENT(.*) ]]
      then
        echo "${BASH_REMATCH[1]}${deployment}${BASH_REMATCH[2]}"
      elif [[ "$line" =~ (.*)IMAGE(.*) ]]
      then
        echo "${BASH_REMATCH[1]}${dockerid}/${deployment}${BASH_REMATCH[2]}"
      else
        echo "$line"
      fi
    done < $template
    echo "---"
  fi
done
