apiVersion: v1
kind: Service
metadata:
  name: servicea-service
  labels:
    app: servicea
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: servicea
---
apiVersion: v1
kind: Service
metadata:
  name: serviceb-service
  labels:
    app: serviceb
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: serviceb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: servicea-config
data:
  serviceB_host: serviceb-service
  serviceB_http_port: "8080"
  lifetime: "0"
  failFrequency: "0"
  MP_Fault_Tolerance_NonFallback_Enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceb-config
data:
  lifetime: "120"
  failFrequency: "10"
